import type { Metadata } from "next";
import { Afacad } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const afacad = Afacad({
  subsets: ["latin"],
  variable: "--font-afacad",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${afacad.className} font-sans`}>
        {children}
      </body>
    </html>
  );
}
